#spring:
#  application:
#    name: jwtAuth
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update # You can set this to create-drop or none depending on your needs
#      format_sql: true
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: UTC # Optional, adjust according to your requirements
